### ISSUE TITLE
ktk.read_c3d doesn't distinguish points between proper points and computed forces/angles/etc., which may lead to scaling and unit error in computed points

### ISSUE THREAD

**Issue by felixchenier** [felixchenier/kineticstoolkit#147]
### Discussed in https://github.com/felixchenier/kineticstoolkit/discussions/146

<div type='discussions-op-text'>

<sup>Originally posted by **gaozelle** March  4, 2023</sup>
After using vicon to collect kinematics data, I found that all kinds of angle data in the c3d data extracted with kineticsToolkit were incorrect. But the EMG and point data are correct.

- The output of the kineticsToolkit looks like this:
```
zzt_moka["Points"].plot("RKneeAngles")
```
![image](https://user-images.githubusercontent.com/31237218/222888228-052d198e-84d4-4e24-8f4c-b4a67cef8eca.png)

- I used pyomeca to extract the angle data of c3d, which is correct:
```
import pyomeca
from pyomeca import Markers
tdata_path = "/Users/macgazelle/Desktop/c3d/zzt-mokka.c3d"
tmarkers = Markers.from_c3d(tdata_path, prefix_delimiter=":")
tmarkers.sel(channel="RKneeAngles", axis = "z").plot.line(x="time")
```
![image](https://user-images.githubusercontent.com/31237218/222886718-c5c6e6dc-fe19-4827-a73d-172e8c4ad625.png)

- It is also correct to use mokka to read the angle of c3d data:
![6751677920446_ pic](https://user-images.githubusercontent.com/31237218/222886889-9ddd7730-5b44-4b1f-bd47-e97ccd0c7557.jpg)

I don't know what the problem is. Please tell me how to convert to the correct angle value. If you have time, please upgrade the kineticsToolkit to calculate the correct angle value.

I'd be happy to help if I could.
Thank you very much.
Thank you also for the kineticsToolkit.

</div>

**Comment by gaozelle** [comment]
@felixchenier I would be happy to provide this C3D file. If it is open sourced, could it be noted that the C3D file was provided by Gao Zhanle from Chengdu Sport University?

**Comment by gaozelle** [comment]
I would be happy to provide this C3D file. If it is open sourced, could it be noted that the C3D file was provided by Gao Zhanle from Chengdu Sport University?
















At 2023-03-18 02:19:37, "Félix Chénier" ***@***.***> wrote:

@gaozelle I'm starting working on this issue. I'm wondering, would you mind if I upload your c3d file on ktk's repository on GitHub, as a test file for unit testing? This is the best way to ensure that this specific issue is solved and stays solved in the future. But obviously, I need your permission to upload this file because this is an open source repository and this file would de facto become public. If you're not sure that you are allowed to say yes, then say no, I'll find another way. Otherwise, it would be much appreciated.
Tx

**Comment by felixchenier** [comment]
Thanks @gaozelle 

I'm still deciding if I'll need it [finally](https://github.com/felixchenier/kineticstoolkit/issues/147#issuecomment-1476133682), but if I do I'll credit you for sure.
